# Configuración para despliegue en Streamlit Cloud
# También funciona localmente al colocarlo en .streamlit/secrets.toml
[GROQ]
API_KEY = "tu_api_key_aqui"

[AGENT]
MODEL_NAME = "llama3-8b-8192"
TEMPERATURE = 0.5
MAX_TOKENS = 8192
