# Configuración para despliegue en Streamlit Cloud
# También funciona localmente al colocarlo en .streamlit/secrets.toml
[GROQ]
API_KEY = "tu API Key"

[AGENT]
MODEL_NAME = "llama-3.3-70b-versatile"
TEMPERATURE = 0.5
MAX_TOKENS = 32768
